
server:
  port: 8005

spring:
  mvc:
    view:
      suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mybatis
    username: root
    password: hpy911213

test:
  value: secondAgent


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.example.springdemo.springdemo.mybatisHandler


stripe:
  publicKey: pk_test_0lY3hK2Vl7lYTOg5MkgKvX8t00yO7d9VJF
  apiKey: sk_test_6e0TErt3Usy0Xmu3ZOaYwFe900cl9ANZNh
  webhookSecret: whsec_qmI0TqmtFOAbNYsMRe2QzwyyZ1B2wGy2
  homeUrl: http://test.youxiu326.xin/api/stripe/notice