
server:
  port: 8005

spring:
  mvc:
    view:
      suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  aop:
    proxy-target-class: true




test:
  value: secondAgent
