
server:
  port: 8005

spring:
  mvc:
    view:
      suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mybatis
    username: root
    password: hpy911213

test:
  value: secondAgent


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.example.springdemo.springdemo.mybatisHandler