
server:
  port: 8005

spring:
  mvc:
    view:
      suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/neo
    username: root
    password: hpy911213

test:
  value: secondAgent


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-handlers-package: com.example.springdemo.springdemo.mybatisHandler


stripe:
  publicKey: pk_test_l3GlhrUNZQ40S0jREI7laODj00wiYhu92J
  apiKey: sk_test_vnMWnTEIstABFNSeTs9pqNbb00bvJ6eJnK
  webhookSecret: whsec_wpBufCNGtdvYzgQOrD9MY7dIvUekDSxi
  homeUrl: http://test.youxiu326.xin/api/stripe/notice